wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.17.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725232745
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 13
      - 23
      4: 3.12.3
      5: 0.17.8
      8:
      - 5
      13: linux-x86_64
lstm_hidden_size:
  desc: null
  value: 32
dnn_hidden_sizes:
  desc: null
  value:
  - 32
  - 16
batch_size:
  desc: null
  value: 128
learning_rate:
  desc: null
  value: 0.0001
